### ISSUE TITLE
Review architecture for share & save

### ISSUE THREAD

**Issue by andricDu** [overture-stack/minime#1]
Ego integration, language, deployment, etc...

**Comment by andricDu** [comment]
Whatever we do, this will be critical: https://docs.aws.amazon.com/lambda/latest/dg/test-sam-local.html

It supports all the Lambda runtimes. I'm starting to lean back to Java 8.

**Comment by andricDu** [comment]
If we port the prototype to our Java Lambda monorepo, we can just use the well defined abstractions and Ego infrastructure we've done, and then we can test all the lambda stuff together.

**Comment by phuongmy** [comment]
Just a note from a user perspective: when the user shares a query, he should not see this query in "My saved queries". He should only see queries that he saved using the Save query button.

**Comment by alex-wilmer** [comment]
> Just a note from a user perspective: when the user shares a query, he should not see this query in "My saved queries". He should only see queries that he saved using the Save query button

@phuongmy this is an issue for the kids-first portal. this repo already has the needed flag for that

**Comment by andricDu** [comment]
After talk with Jon, due to the frequency and needs of using minime functionality, we will stand it up as a microservice.

**Comment by andricDu** [comment]
Talked with @ra-ver ¸ will go with a base10 to base36 scheme. This gives us an ID space of 9,223,372,036,854,775,807 unique short URLs where the max short ID is 1Y2P0IJ32E808

**Comment by andricDu** [comment]
Closing this issue as implementation is underway.

Will put implementation in second ticket.
